# This is a simple example of how to read in the h5 files generated by the droppy code. 
# RECOMMENDED: Copy this code to another file rather than editing this example.

import sys
sys.path.insert(0, r'DIR OF THE CODE') # specify the source directory of the code
import io_methods as io
import numpy as np
from matplotlib import pyplot as plt

##########################################################################

target=r'NAME_HERE(no extension)' # h5 file for reading 

dataset_names = ["Theta", "Radius","Time", "xc", "yc"] # Datasets to pull from the h5 file

resolution = 1 # Read in resolution from the file, 1=all
data = io.load_datasets_h5py(target, dataset_names, resolution=resolution)

times = np.linspace(0,data['Time'].ravel()[-1],50) # time to loop through and find positions and sizes of droplets

cmap = plt.get_cmap("hot")
colours = cmap(np.linspace(0, 1, data['Radius'].shape[1]))

for droplet in range(data['Radius'].shape[1]):
    for tdx, t in enumerate(times):
        print("time: ", t)
        print("_____________")
        t_i = np.argwhere(t>=data['Time'].ravel())[-1][0]
        r0 = data["Radius"][t_i,droplet] # metres
        radii = r0[~np.isnan(r0)] # metres
        theta = data["Theta"][t_i,droplet] [~np.isnan(r0)] # degrees
        plt.scatter(t_i, radii, color=colours[droplet])

plt.xlabel("Time (s)")
plt.ylabel("Droplet radius (m)")
plt.show()





